[Project]
cubic_version = 2026.08.108-release~202608210008~ubuntu22.04.1
first_version = 2026.08.108-release~202608210008~ubuntu22.04.1
create_date = 2026-08-26 17:50
modify_date = 2026-08-26 18:07
directory = /home/aitorsb/Downloads/CUBIC/UBUNTU CINNAMON

[Original]
iso_file_name = ubuntucinnamon-26.04-desktop-amd64.iso
iso_directory = /home/aitorsb/Downloads
iso_volume_id = Ubuntu-Cinnamon 26.04 amd64
iso_release_name = Resolute Raccoon
iso_disk_name = 

[Custom]
iso_version_number = 1.0
iso_file_name = prismcore-26.04-1.0-desktop-amd64.iso
iso_directory = /home/aitorsb/Downloads/CUBIC/UBUNTU CINNAMON
iso_volume_id = PrismCore 26.04
iso_release_name = v1.0
iso_disk_name = PrismCore 26.04 "v1.0"

[Layout]
casper_directory = casper
squashfs_directory = casper
squashfs_file_name = 
manifest_file_name = filesystem.manifest
minimal_remove_file_name = 
standard_remove_file_name = 
size_file_name = filesystem.size
minimal_squashfs_file_name = minimal.squashfs
minimal_manifest_file_name = minimal.manifest
minimal_size_file_name = minimal.size
standard_squashfs_file_name = minimal.standard.squashfs
standard_manifest_file_name = minimal.standard.manifest
standard_size_file_name = minimal.standard.size
install_sources_file_name = install-sources.yaml
live_squashfs_file_name = minimal.standard.live.squashfs
live_manifest_file_name = minimal.standard.live.manifest
live_size_file_name = minimal.standard.live.size
live_generic_squashfs_file_name = 
live_generic_manifest_file_name = 
live_generic_size_file_name = 

[Status]
is_success_analyze = True
is_success_copy = True
is_success_extract = True
iso_template = 789C8D51CD8E832010BEFB14DCBCEC54C5D6AA0FB25732C06848500CD0266DD3775FFFB6E96EF6B007087C03F3FD0C7CB2F47175F6329030FA992600BDBF480E83F40CC08C91FC156D6B9D422BBAD0E6018A5368EFE49D98DF4CF1633DF6536CD387742E0A33604F421B4F2A3A7F7B6613FA68A27123140733F40BC7E45D9CCBE64A3004ED0258946413783D15EA66055AD38FCC75DD7B61BE068AACA8E636B300E89C57040B334A4B09E034D1A8C5EB03E38CD7E792A32A8AAEAB352F0A894799E798ABA6A479C9BF8D6A2872DE9C74FB0F637C37B691D3462F302CB92460C29AD506C6DB440C39E63A274927D994E5F1589F555ED5B292675E358D3A27A0589A2DAC078511AD5B9ACB1DCA960965A6AC2B985446761663A2DB158C0E68B8D8359064DDC13AD410CC9DD87147CCD839D8F3DAE7FDC213F8EE0868E3DE8758FA96D10F97DB54788BD6CE49FD12F005676ED19A
iso_checksum = 
iso_checksum_file_name = 

[Options]
update_os_release = True
has_minimal_install = False
boot_configurations = boot/grub/grub.cfg, boot/grub/loopback.cfg
compression = xz

